"""Adapter contracts. Source, Fusion LOAD and Fusion READ-BACK are distinct
first-class adapters (ADR-0009). Vendor specifics are validated at pilot."""
from __future__ import annotations
from typing import Protocol, Iterable, Any

class SourceAdapter(Protocol):
    def test_connection(self) -> bool: ...
    def list_tables(self) -> list[str]: ...
    def column_metadata(self, table: str) -> list[dict]: ...  # name,type,length,pk,description
    def extract(self, sql: str) -> Iterable[dict]: ...        # read-only; never writes source

class TargetLoadAdapter(Protocol):
    def validate(self, payload: Any) -> dict: ...
    def submit(self, payload: Any, idempotency_key: str) -> dict: ...  # returns file/job ids
    def poll(self, job_id: str) -> dict: ...
    def errors(self, job_id: str) -> list[dict]: ...
    def replay_failed(self, job_id: str, failed_subset: Any, idempotency_key: str) -> dict: ...

class TargetReadBackAdapter(Protocol):
    """Re-reads ACTUAL target state for reconciliation (ADR-0009)."""
    def read_back(self, object_name: str, keys: list[str]) -> Iterable[dict]: ...
    def coverage(self) -> dict: ...  # records read-back vs expected; flags gaps
